### ISSUE TITLE
Paraguay: Contract Amendements

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/implementation-and-extensions#8]
From conversations with @juanpane

> In Paraguay, when a contract is amended to extend the contract value, this results in a new contract ID, and effectively a new contract. How would this be modelled in OCDS?

For example, [see this contracting process](https://www.contrataciones.gov.py/datos/visualizaciones/etapas-licitacion?id_llamado=265962) where the right-hand blue circle is an amendment, extending the original contract.

![screen shot 2015-09-16 at 20 07 52](https://cloud.githubusercontent.com/assets/342624/9915392/aecb1e52-5cae-11e5-9824-a6eb616e568b.png)

In OCDS the way to model this would be to include a full new entry in the `contracts` array for the amendment (which constitutes a new contract, with a new contractID), with both the original contract and the subsequent contract referencing the same `awardID`. 
## Discussion

This raises a question about how much information should be duplicated between the two contract array entries. For example, if Contract A is for $1000 to deliver 10 chairs, but then there is an amendment which results in a new contract (Contract B) for $200 to cover the increased price of chairs should Contract B include an items array with 10 chairs in, or should it leave the items array blank.

In the first case, it appears that 10 chairs are now being bought for $100.

In the second case, it appears that $100 is being spent on nothing. 

One way around this would be to introduce a property called something like: `extendsContract` which could be used to refer back to a parent contract. 

@juanpane Can you point to a current example of the data for an amended contracting process so I can check the assumptions above?

How important would this extendsContract type of property be do you think?

**Comment by juanpane** [comment]
hi, in what follows I will try explain the logic behind the amendments in Paraguay

Considering the 3rd key principle for Conformance and extension [1]:
_Its usage of this specification's terms must be consistent with the semantics of those terms._

This states that the use of a property must be consistent with the semantics of its specification

Considering the specification of the Amendment from [2]:
_The amendment block in each of tender, award and contract blocks provides the ability to explicitly declare changed fields, their former values, and to provide an explanation for the change._

However in Paraguay the Amendments of the contracts work in the following way:
- An amendment, in general, does not change any of the original contract information.
- All amendments are related to a contract
- A contract can have several amendments
- Amendments have types, and in general they modify the contract value or contract period, i.e., most amendments are of type "extension in value" or "extension in period", but there are others. The types of amendments in Paragay are:
  - Extension in value: is required when the Client and Supplier, require more items that what was originally awarded, which implies more money.
  - Extension in period: (more time) when the period or deadline of what was originally awarded is extended.
  - Adjustments: when the prices of the items originally awarded change, maintaining unaltered the number of items awarded (now the items cost more money).
  - Other: Any other change, addition or amendment to the already signed contracts.
- The amendment has other associated information attached to the administrative procedure, for example, title, description, type, id, code, date of signature, ...
- If there is an amendment related to an increase of value, for example, if the original contract was of 1000, and the amendment is of 20%, the amendment value would be 200. This creates a new administrative act, similar to a contract, that has its own budget and may even come from a different fiscal year. Payments of this amendment are done against the amendment id, not the against the contract id that was modified (see how the blue circles, representing amendments are filled in independently from the main contract in [3], represented in orange)
- The cases in which the amendment needs to modify the contract value, is when there is a decrease of the total contract value, but this also normally implies that there is a change in the list of items, typically, removing items. The current transactional system, however, only keeps track of this sort of changes in the audit tables, not in the transactional system that can use this versioned information.

Considering cases of amendments for adding values or period, it is necessary to create a new property for the Contract class, that would be an array of this newly defined amendment, since we cannot use the already defined "amendment" property because the semantics is different (there is no change in the values of the properties, there is an addition)

Proposal:
The resulting class instance could look something like this. This is based on the information already available in the transactional system. The names of the attributes are suggested, if there are better names please propose them.

``` json
{
  "ammendment": {
    "id": "207002-armin-hahner-stollmaier-21-renovacion",
    "extendsContract.id": "207002-armin-hahner-stollmaier-21",
    "type": "Renovación de Alquiler de Inmueble",
    "title": "Ad Referendum - Alquileres para la SNNA",
    "description": "Example description",
    "code": "RL-12001-12-0012",
    "dateSigned": "2012-03-14 16:58:40.265507",
    "status": "active",
    "added_value": {
      "currency": "PYG",
      "amount": 12780000
    },
    "new_period": {
      "startDate": "02/01/2012 ",
      "endDate": "02/01/2013"
    },
  }
}
```

References:

```
[1]: http://ocds.open-contracting.org/standard/r/1__0__0/en/key_concepts/conformance_and_extensions/
[2]: http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/reference/#amendment
[3]: http://www.mopc.gov.py/mopcweb/BM/IGAP/index.html
```

**Comment by timgdavies** [comment]
Thanks @juanpane for setting this out so clearly. 

You are right that your case does not fit with the current semantics of `amendment`. 

It looks to me like your amendments are much closer to being extension `contract`s, and so my inclination is to still explore whether we can re-use and extend the existing `contract` object to meet your needs here.

The key consideration I'm working from here is on how users and generic systems not fully aware of the complexities of the Paraguay data would interpret the data, and which questions would be transparently answered by different models.

In the case you propose, any consumer of the data would need to be explicitly aware of the new/extended `amendment` class in order to understand the full value of transactions with a given supplier. However, if we model each amendment as a new `contract` in the contracts array, then anyone looking for the total value of contracts, of timeline of contracts, with a given supplier, or for a given buyer, will get an accurate report of this. Each `contract` object also has it's own `implementation` block, allowing for transactions to be recorded against that specific contract, and these amendment contracts can, if required, live in their own releases. The only limitation I can see based on what you have described above is that we don't have an explicit linkage right now between the amendment contracts and the budgets they are drawing on (this is a limitation of the budget section in the current planning block, and could be addressed in 1.1 potentially). 

The only thing I can see with this modelling is that it may put the count of contracts out in some analysis, depending on whether amendments are to be considered as unique contracts or not (where, from what you've said, it appears both interpretations could be valid). 

To give a worked example, the amendment would act as an extra entry in the `contracts` array, with the addition of a few extra properties:

``` json
contracts: [ 
    {
     "# Original contract"
    },
    {
            "id": "207002-armin-hahner-stollmaier-21-renovacion-ext1",
            "awardID": "207002-armin-hahner-stollmaier-21-renovacion-award",
            "extendsContractID":"207002-armin-hahner-stollmaier-21-renovacion",
            "title": "Ad Referendum - Alquileres para la SNNA (Amends contract 207002)", 
            "description": "Example Description",
            "status": "active",
            "period": {
                "startDate": "2012-01-02T23:59:59+00:00",
                "endDate": "2013-01-02T23:59:59+00:00"
            },
            "value": {
                "amount": 12780000,
                "currency": "PYG"
            },
            "items": [
                {
                    "id": "01",
                    "description": "Renovación de Alquiler de Inmueble",
                    "classification": {
                        "scheme": "CPV",
                        "id": "70000000-1",
                        "description": "Real Estate Services",
                        "uri": "http://cpv.data.ac.uk/code-70000000"
                    }
                }
            ],
            "dateSigned": "2012-03-14T16:58:40+00:00",
            "implementation": {
                "transactions": [
                    {
                        "id": "01",
                        "source": "Budget Identifier",
                        "date": "2012-03-14T16:00:00+00:00",
                        "amount": {
                            "amount": 2780000,
                            "currency": "PYG"
                        },
                        "providerOrganization": {
                            "scheme": "PY-GOV",
                            "id": "MinFinance",
                            "legalName": "Ministry of Finance"
                        },
                        "receiverOrganization": {
                            "scheme": "PY-COM",
                            "id": "12345678",
                            "legalName": "Acme Company"
                        },
                        "uri": "http://payments.gov.py/transactional-link-data/example/21951235"
                    }
                ]
           }
        }
]
```

Notes:
- I considered adding an `isAmendment` or `contractType` property to explicitly declare that this is an amendment type of contract - but felt that this was redundant when the `extendsContractID` exists. 
- I wasn't sure what the semantics of `code` in your example were. Is this a unique identifier for the amendment, such that it could function as the ID? If not, perhaps a more explicit property name to make clear what kind of code it is would be useful. 
- I explicitly added text to the title explaining that this was an extension of a contract. Doing this would help any consuming applications that are not aware of the `extendsContractID` property to display this information in a more intelligible way to users (i.e. users could easily understand the relationships between the contracts from a list of them)
- This example shows how the transactions 'source' could be used to indicate the budget this comes from. 

Thoughts?

**Comment by juanpane** [comment]
thank you very much @timgdavies. I'll share this with the National Procurement office from Paraguay and get back to you ASAP

Regards

**Comment by juanpane** [comment]
quick reply about code:
"code": "RL-12001-12-0012",

is the contract code issued by DNCP and that is used by the Ministry of Finance (MoF) to pay contracts, so, most likely, the implementation data (payments done by MoF) will have this "contractCode". Furthermore, all the payments that are not processed by the MoF normally have this contractCode in all the other ministries. 

As a side note, thanks to this code I could manage to create the visualization here http://www.mopc.gov.py/mopcweb/BM/IGAP/index.html. Since in the ministry of public works I only had the payments with their contracCodes, but not information about the contracts themselves. Using the open data from DNCP I retrieved all the missing information. So, this contractCode is pretty important :)

What would you suggest for the name of this attribute?
This would need to go into all the contracts, even the ones that are not amendments

Cheers

**Comment by timgdavies** [comment]
I think `contractCode` probably works as an extended property that is a bit more explicit. As this would only be used in Paraguay (i.e. the semantics of it are specific to your context) you could be even more specific, and use something like `DNCPContractCode` if that would make it clearer to users what this is without needing to look in depth at documentation.

**Comment by juanpane** [comment]
Hi, we checked the amendments in Paraguay and the proposal sent by @timgdavies 
The data about amendments will be published as contracts, as suggested, including the following new attributes:

``` javascript
        "extendsContractID": "207002-armin-hahner-stollmaier-21",
        "dncpContractCode": "RL-12001-12-0012",
        "dncpAmendmentType": "Renovación de Alquiler de Inmueble",
```

Where:
- **extendsContractID** references the parent contract
- **dncpContractCode** is the paraguayan contract code from DNCP (Dirección Nacional de Contrataciones Públicas del Paraguay)
- **dncpAmendmentType** is the type of amendment that can be selected from a predefined list, which will be explained in the documentation
- the **title** will have a prefix with the word "Adenda", where the suffix will be the name of the parent contract referenced by **extendsContractID**.

Furthermore, the **initiationType** attribute from the correspondent realease will be set to "contractAmendment".

The resulting json example for the releasePackage is:

``` javascript
{
  "uri": "https://contrataciones.gov.py/datos/doc/modificaciones-contrato/207002-armin-hahner-stollmaier-21-renovacion",
  "publishedDate": "2015-11-18T17:52:42-0300",
  "publisher": {
    "scheme": "",
    "id": "",
    "legalName": "Dirección Nacional de Contrataciones Públicas del Paraguay",
    "uri": "https://contrataciones.gov.py/datos"
  },
  "license": "https://creativecommons.org/licenses/by/4.0/",
  "publicationPolicy": "",
  "releases": [
    {
      "language": "es",
      "ocid": "ocds-03ad3f-207002",
      "id": "207002-armin-hahner-stollmaier-21-renovacion-contractAmendment",
      "date": "2015-11-18T17:52:42-0300",
      "tag": [
        "contractAmendment"
      ],
      "initiationType": "contractAmendment",
      "contract": {
        "id": "207002-armin-hahner-stollmaier-21-renovacion",
        "extendsContractID": "207002-armin-hahner-stollmaier-21",
        "dncpContractCode": "RL-12001-12-0012",
        "dncpAmendmentType": "Renovación de Alquiler de Inmueble",
        "title": "Adenda. Ad Referendum - Alquileres para la SNNA",
        "status": "active",
        "value": {
          "amount": 12780000,
          "currency": "PYG"
        },
        "dateSigned": 2013-04-05 12:00:00,
        "documents": [
          {
            "id": "QEtHkufJB08%3D",
            "documentType": "Contrato Renovación",
            "title": "contrato_armin_s_1331755085630.zip",
            "language": "es",
            "url": "https://www.contrataciones.gov.py/doc/download/modificaciondecontrato/QEtHkufJB08%3D",
            "format": "application/zip"
          },
          {
            "id": "8j9UtJdIVKc%3D",
            "documentType": "Dictamen Renovación",
            "title": "dictamen_1331755002227.PDF",
            "language": "es",
            "url": "https://www.contrataciones.gov.py/doc/download/modificaciondecontrato/8j9UtJdIVKc%3D",
            "format": "text/plain"
          },
          {
            "id": "tbdR5FGj9H4%3D",
            "documentType": "Resolución Renovación",
            "title": "resol_de_renovacion_de_contratos_1331755012802.zip",
            "language": "es",
            "url": "https://www.contrataciones.gov.py/doc/download/modificaciondecontrato/tbdR5FGj9H4%3D",
            "format": "application/zip"
          }
        ],
        "period": {
          "startDate": "",
          "endDate": ""
        }
      }
    }
  ]
}
```

Do you have any comments and/or further suggestions?

**Comment by timgdavies** [comment]
This looks good.

The use of a new `initiationType` is something we'll need to look at [adding to the initiation type codelist](http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/codelists/#initiation-type) to avoid that failing validation. 

I'm guessing this is a mock-up, as there are a few invalid bits, like `contracts` needing to be an array of contract objects, and one of the dates.

**Comment by timgdavies** [comment]
I've just been looking at the `initiationType` issue a bit more whilst writing up a proposal to add this to codelists. However in doing so I've realised that this is a property of the contracting process as a whole, rather than the specific release, or contract amendment being issued.

So - I would suggest we stick to `"initiationType": "tender"`, and that the releaseTag is treated as the way to recognise this as a contractAmendment clearly.

**Comment by juanpane** [comment]
thanks @timgdavies for the quick reply

we'll fix:
- contracts to be sets
- and 

``` javascript
      "tag": [
        "contractAmendment"
      ],
      "initiationType": "tender",
```

is there anything else?

**Comment by juanpane** [comment]
this is very nice to hear, as the [LOTED2](http://www.semantic-web-journal.net/content/loted2-ontology-european-public-procurement-notices-0) ontology is in "theory" the model for the european tender system. We can definitely talk more about this

**Comment by timgdavies** [comment]
Only two things I can see from running through the validator:

1) `"dateSigned` doesn't seem to be formatted right;

2) The validator asks for `publisher` to have a `name` (required field) as well as the optional `legalName` field. In your case, I guess these might be duplicates - but this handles for the fact that consuming apps will tend to go to `name` for display purposes.

**Comment by juanpane** [comment]
we'll check these issues and fix them ASAP
Many thanks

**Comment by juanpane** [comment]
is there a service for the validator that we could use for automating the validation process?
